sudo: required
services:
  - docker

before_install:
  - docker build -t hugorla/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run hugorla/react-test npm test -- --coverage

after_success:
  - docker build -t hugorla/multi-client ./client
  - docker build -t hugorla/multi-nginx ./nginx
  - docker build -t hugorla/multi-server ./server
  - docker build -t hugorla/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push hugorla/multi-client
  - docker push hugorla/multi-nginx 
  - docker push hugorla/multi-server
  - docker push hugorla/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-962899211982"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
